2022-08-27T11:53:35Z Bot is starting up...
2022-08-27T11:53:37Z Bot is ready.
2022-08-27T11:53:41Z ERROR TRACE:
Traceback (most recent call last):
  File "main.py", line 625, in test
    print(f'{utcTimestamp()} DEBUG partialMsg = {ctxpartialMsg}')
NameError: name 'ctxpartialMsg' is not defined
# TRACE END

